### ISSUE TITLE
CSS Sourcemaps in productie

### ISSUE THREAD

**Issue by MicheleNL** [mat1th/meesterproef#35]
Zag hier (https://posters.dolstra.me/css/style.css) dat je sourcemaps meekomen, op je livesite. Is dat bewust of zou je ze liever alleen in een local of dev omgeving gebruiken?

Overigens is het voor het bekijken en beoordelen van CSS wel handig om de output CSS te bekijken zonder dat deze geminified is. Je kunt ook twee versies maken en met bijv. een gulp-rename een style.min.css maken.

**Comment by mat1th** [comment]
Ja dat klopt, het was nu vooral voor mij zelf. Bedankt voor de gulp tip!
