### ISSUE TITLE
Foldername: components

### ISSUE THREAD

**Issue by MicheleNL** [mat1th/meesterproef#37]
Mooi dat je je CSS files organiseert door ze bijv in een map te stoppen, wel twijfel ik of ik 'components' een logische plek vind voor sommige bestanden, maar dat is meer een file architecture ding. Components zijn vaak de stukjes die je kunt hergebruiken op je website, dus buttons of tables of icons etc. Andere elementen zijn vaak een module, of misschien een layout. Als je dit interessant vind zou je hier nog eens naar kunnen kijken :)

**Comment by mat1th** [comment]
Daar heb je gelijk in. Bedankt voor de tip!
