### ISSUE TITLE
:hover & :focus

### ISSUE THREAD

**Issue by MicheleNL** [mat1th/meesterproef#38]
Als je :hover gebruikt kan het vaak ook nuttig zijn om de :focus style ook te definieren. Bijv door dezelfde styling op beide pseudo-classes toe te passen. Zo hebben mensen die met een toetsenbord door je site heen tabben ook visuele feedback.

**Comment by mat1th** [comment]
hij elk hover element heb ik nu ook een focus gebruikt, soms een eigen opmaak en soms gewoon de hover opmaak
