### ISSUE TITLE
Semantische HTML in je templates

### ISSUE THREAD

**Issue by MicheleNL** [mat1th/meesterproef#40]
`<div class="name">` 

Misschien kan dit ook een ander HTML element zijn? Iets semantisch misschien.. Check je HTML nog even op dit soort dingen. 

```
<div class="name">
     <h2>Icons presentatie</h2>
     <small>06 dec.  - 20 jun. 2020</small>
</div>
```

Ook heeft `<small>` een bepaalde semantische waarde, vaak gebruikt voor disclaimers of copyright etc. Ook voor deze content is vast iets voor te vinden, met meer betekenis. 

http://html5doctor.com/ vind ik persoonlijk een leuke site om meer te lezen over de verschillende HTML5 elementen.

**Comment by mat1th** [comment]
Ik heb meer html elementen gebruikt en bij jou voorbeeld een figurecaption
