### ISSUE TITLE
Loader.css keyframe animation

### ISSUE THREAD

**Issue by MicheleNL** [mat1th/meesterproef#42]
Niet perse fout hoor, maar wellicht vind je dit ook interessant, dus doe ermee wat je wil :)

In je @keyframes loading animatie, animeer je bepaalde properties, zoals width en left. Er zijn een aantal properties die heel geschikt zijn om te animeren, en sommige wat minder, in het kader van performance. Sommige properties die geanimeerd worden kunnen zorgen voor repaints of reflows, waardoor delen van de pagina opnieuw gerenderd moeten worden, dat kan ten koste gaan van de (perceived) performance.

Properties die 'goedkoop' zijn om te animaten of transitionen zijn bijv:

- opacity
- transform: rotate
- transform: scale                
- transform: translate          
- filter

Dit is een erg leuk filmpje van Fronteers Spring Conference dat daarover gaat:

https://vimeo.com/163185189

**Comment by mat1th** [comment]
Ik wist niet dat het zelfs voor repaints kon zorgen. Interessant filmpje! 

Adobe heeft er ook nog een goed artikel over geschreven. [Link](http://blogs.adobe.com/webplatform/2014/03/18/css-animations-and-transitions-performance/)
