### ISSUE TITLE
Semantische classnames

### ISSUE THREAD

**Issue by MicheleNL** [mat1th/meesterproef#43]
```
.bold {
    font-size: 1em;
    font-weight: bold;
}
```
Dit soort class names kwam ik regelmatig tegen in je code. Bijv .center, .right, .content-header.block  . Probeer markup en styling zoveel mogelijk gescheiden te houden. 
Kijk of je voor dit soort dingen een class name kan bedenken die iets zegt over de content, ipv over de styling. Misschien kun je voor dit soort dingen ook af met een `<strong>` of `<em>` tag, of kun je een class name bedenken die de lading beter dekt (waarom is de tekst bold? Misschien is het important text, of stand out text, of iets in die richting)

**Comment by mat1th** [comment]
Ik heb ze verwijdert. Nu heb ik html elementen of andere class namen gebruikt
